// health.ts is the one place that turns daemon facts into a claim about the
// user's traffic, and every failure this project has found lives in the gap
// between "the VPN is on" and "the LAN is actually captured". So the thing
// worth asserting is not that the function returns the strings it returns —
// it is that **no input can make it claim protection it has not verified**,
// and that the two dwells which decide when it may accuse the router are
// bounded at both ends.
//
// Everything here drives the exported behaviour: `health()`, the dwell fold,
// and the age arithmetic. Nothing reaches inside them.

import { describe, expect, it } from "vitest";
import {
  APPLY_SUPPRESSES_ALARM_MS,
  PROXY_DOWN_AFTER_MS,
  PROXY_DOWN_MIN_FRAMES,
  STALE_AFTER_MS,
  captureAgeMs,
  health,
  mayShowOnboarding,
  proxyDownDwellElapsed,
  trackProxyDown,
  type ActionKind,
  type Capture,
  type Level,
  type ProxyDownEvidence,
} from "./health";
import type { MetricsFrame } from "./types";

/** The one sentence that asserts the user is protected. Nothing else in the
 *  module may say it, and this test's job is to prove that. */
const CAPTURED_CLAIM = "Everything leaving this LAN goes through the tunnel.";

/* ===========================================================================
   1. The truth table
   ===========================================================================

   Every combination of the four facts `health()` reads, with the level it is
   allowed to return. 2 intents × 4 capture readings × 2 ages × 2 proxy states
   = 32 cells, written out rather than computed, because a table generated by
   the same reasoning as the code under test proves nothing.

   Read the capture column as: what the watchdog last saw.
     true      — it read the ruleset and our chain was hooked
     false     — it read the ruleset and it was not
     null      — the read itself failed (xtables lock, dead daemon)
     undefined — no watchdog reading has ever reached this browser        */

type CapName = "true" | "false" | "null" | "undefined";
type Age = "fresh" | "stale";
type Proxy = "answering" | "silent";

const CAPTURE: Record<CapName, Capture> = {
  true: true,
  false: false,
  null: null,
  undefined: undefined,
};

type Row = [
  vpn: "on" | "off",
  capture: CapName,
  age: Age,
  proxy: Proxy,
  level: Level,
  code: string,
  covered: boolean,
  loud: boolean,
  action: ActionKind | null,
];

// prettier-ignore
const TRUTH: Row[] = [
  // vpn    capture       age       proxy         level      code           covered  loud   action
  ["on",  "true",      "fresh",  "answering",  "secure",  "CAPTURED",     true,   false, null       ],
  ["on",  "true",      "fresh",  "silent",     "caution", "NO LISTENER",  false,  true,  "stop"     ],
  // A reading too old to be evidence is not a downgraded claim — it is no
  // claim. Both of these were CAPTURED once, on a frame that stopped arriving.
  ["on",  "true",      "stale",  "answering",  "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  ["on",  "true",      "stale",  "silent",     "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  // Verified absent. A dead proxy does not soften this: nothing is being
  // diverted into it, so the traffic is not black-holed, it is on the ISP.
  ["on",  "false",     "fresh",  "answering",  "alarm",   "LEAKING",      false,  true,  "reassert" ],
  ["on",  "false",     "fresh",  "silent",     "alarm",   "LEAKING",      false,  true,  "reassert" ],
  ["on",  "false",     "stale",  "answering",  "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  ["on",  "false",     "stale",  "silent",     "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  // The read failed. Age is meaningless — a failed read does not become more
  // or less failed with time — so all four cells are the same state.
  ["on",  "null",      "fresh",  "answering",  "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  ["on",  "null",      "fresh",  "silent",     "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  ["on",  "null",      "stale",  "answering",  "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  ["on",  "null",      "stale",  "silent",     "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  // Never checked. Identical treatment to a failed check, on purpose: "we have
  // not looked yet" and "we looked and got nothing" are both "we do not know".
  ["on",  "undefined", "fresh",  "answering",  "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  ["on",  "undefined", "fresh",  "silent",     "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  ["on",  "undefined", "stale",  "answering",  "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  ["on",  "undefined", "stale",  "silent",     "unknown", "UNVERIFIED",   false,  true,  "reassert" ],
  // VPN off is deliberately ONE state, not two. A capture still installed with
  // the VPN off is the designed behaviour (sing-box dials those connections
  // out directly), so it must not fire an alarm on every single off — and a
  // capture with a *dead* sing-box behind it, which really would black-hole
  // the LAN, is invisible from here: the daemon publishes `available: false`
  // unconditionally once vpn_on is false, without ever asking sing-box.
  ["off", "true",      "fresh",  "answering",  "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "true",      "fresh",  "silent",     "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "true",      "stale",  "answering",  "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "true",      "stale",  "silent",     "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "false",     "fresh",  "answering",  "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "false",     "fresh",  "silent",     "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "false",     "stale",  "answering",  "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "false",     "stale",  "silent",     "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "null",      "fresh",  "answering",  "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "null",      "fresh",  "silent",     "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "null",      "stale",  "answering",  "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "null",      "stale",  "silent",     "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "undefined", "fresh",  "answering",  "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "undefined", "fresh",  "silent",     "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "undefined", "stale",  "answering",  "off",     "DIRECT",       false,  false, "start"    ],
  ["off", "undefined", "stale",  "silent",     "off",     "DIRECT",       false,  false, "start"    ],
];

/** Comfortably inside the window; the boundary gets its own tests below. */
const FRESH_MS = 1_000;
const STALE_MS = STALE_AFTER_MS + 1;

function factsFor(row: Row) {
  const [vpn, capture, age, proxy] = row;
  return {
    vpnOn: vpn === "on",
    capture: CAPTURE[capture],
    ageMs: age === "stale" ? STALE_MS : FRESH_MS,
    proxyDown: proxy === "silent",
  };
}

describe("the truth table", () => {
  it("covers the whole cross product, once each", () => {
    const keys = TRUTH.map((r) => r.slice(0, 4).join("/"));
    expect(new Set(keys).size).toBe(keys.length);
    expect(keys.length).toBe(2 * 4 * 2 * 2);
  });

  for (const row of TRUTH) {
    const [vpn, capture, age, proxy, level, code, covered, loud, action] = row;
    it(`vpn ${vpn} · capture ${capture} · ${age} · proxy ${proxy} → ${code}`, () => {
      const h = health(factsFor(row));
      expect(h.level).toBe(level);
      expect(h.code).toBe(code);
      expect(h.covered).toBe(covered);
      expect(h.loud).toBe(loud);
      expect(h.action?.kind ?? null).toBe(action);
      // Every state has to say something in plain language, whatever it is.
      expect(h.claim.length).toBeGreaterThan(0);
      expect(h.detail.length).toBeGreaterThan(0);
    });
  }
});

describe("no cell claims protection it has not verified", () => {
  const cells = TRUTH.map((row) => ({ row, facts: factsFor(row), h: health(factsFor(row)) }));

  it("says the protected sentence only where all four facts allow it", () => {
    for (const { row, facts, h } of cells) {
      const earned =
        facts.vpnOn &&
        facts.capture === true &&
        facts.ageMs <= STALE_AFTER_MS &&
        !facts.proxyDown;
      expect(
        h.claim === CAPTURED_CLAIM,
        `${row.slice(0, 4).join(" / ")} claimed: ${h.claim}`,
      ).toBe(earned);
    }
  });

  it("keeps `covered` and the level in lockstep — one flag, one state", () => {
    for (const { h } of cells) {
      expect(h.covered).toBe(h.level === "secure");
      expect(h.covered).toBe(h.claim === CAPTURED_CLAIM);
    }
  });

  it("never claims coverage while the VPN is off, whatever the capture says", () => {
    for (const { row, h } of cells) {
      if (row[0] === "off") expect(h.covered).toBe(false);
    }
  });

  it("never leaves a loud state without a way out of it", () => {
    // A full-width alarm the user cannot act on is a dead end, and the two
    // states that shout are exactly the ones where doing nothing is costly.
    for (const { h } of cells) {
      if (h.loud) expect(h.action).toBeDefined();
      // …and the reverse: a verified-covered state must not interrupt.
      if (h.covered) expect(h.loud).toBe(false);
    }
  });

  it("offers `stop`, not `reassert`, for the black hole", () => {
    // Re-asserting a capture that is already installed is what the daemon is
    // doing on its own every 30 s; the only thing that ends a black hole from
    // here is letting the watchdog give up and remove it.
    const blackHole = health({
      vpnOn: true,
      capture: true,
      ageMs: FRESH_MS,
      proxyDown: true,
    });
    expect(blackHole.action).toEqual({ label: "Turn VPN off", kind: "stop" });
  });

  it("explains the still-installed capture in the off state, and only there", () => {
    const off = (capture: Capture) =>
      health({ vpnOn: false, capture, ageMs: FRESH_MS, proxyDown: false }).detail;
    expect(off(true)).toContain("capture is still installed");
    expect(off(false)).toContain("No capture rules are installed");
    expect(off(null)).toContain("could not be read");
  });
});

/* ===========================================================================
   2. The staleness boundary
   =========================================================================== */

describe("staleness", () => {
  const fresh = { vpnOn: true, capture: true as Capture, proxyDown: false };

  it("is the boundary itself, not a value near it", () => {
    expect(health({ ...fresh, ageMs: STALE_AFTER_MS - 1 }).level).toBe("secure");
    // Exactly at the constant is still evidence: the comparison is `>`.
    expect(health({ ...fresh, ageMs: STALE_AFTER_MS }).level).toBe("secure");
    expect(health({ ...fresh, ageMs: STALE_AFTER_MS + 1 }).level).toBe("unknown");
  });

  it("degrades a claim to `unknown` rather than letting it persist", () => {
    // This is the whole point of the constant. A wedged daemon or a dead
    // WebSocket leaves the last frame in place (store.applyMetrics keeps it and
    // only flips `available`), so without this the headline goes on asserting
    // CAPTURED from a reading nothing has refreshed in minutes.
    const h = health({ ...fresh, ageMs: STALE_MS });
    expect(h.level).toBe("unknown");
    expect(h.covered).toBe(false);
    expect(h.claim).not.toBe(CAPTURED_CLAIM);
  });

  it("degrades a verified LEAK the same way — staleness is not selective", () => {
    // It would be tempting to let an alarm persist. It must not: the evidence
    // for it has expired too. It stays loud and still offers the repair, so
    // nothing is lost but the certainty.
    const h = health({ vpnOn: true, capture: false, ageMs: STALE_MS, proxyDown: false });
    expect(h.level).toBe("unknown");
    expect(h.loud).toBe(true);
    expect(h.action?.kind).toBe("reassert");
  });

  it("says in words that the reading is memory, with its age", () => {
    const h = health({ ...fresh, ageMs: 120_000 });
    expect(h.detail).toContain("120s old");
    expect(h.detail).toContain("memory, not observation");
  });

  it("cannot go stale on a reading that was never a claim", () => {
    // `null` and `undefined` are not stale-able: a failed read does not decay
    // into a different kind of unknown, and marking it stale would imply there
    // had been something to expire.
    for (const capture of [null, undefined] as Capture[]) {
      const h = health({ vpnOn: true, capture, ageMs: 10 * STALE_MS, proxyDown: false });
      expect(h.level).toBe("unknown");
      expect(h.detail).not.toContain("memory, not observation");
    }
  });

  it("is three missed watchdog ticks — the reason for the number", () => {
    // The watchdog reads the ruleset every 30 s. Short enough that a wedged
    // daemon cannot hold a green headline; long enough not to flicker on one
    // late tick. If either side of that moves, this stops being true.
    expect(STALE_AFTER_MS).toBeGreaterThan(2 * 30_000);
    expect(STALE_AFTER_MS).toBeLessThan(4 * 30_000);
  });
});

describe("captureAgeMs", () => {
  const frame = (f: Partial<MetricsFrame>): MetricsFrame => ({
    available: true,
    history: [],
    ...f,
  });

  it("is null when no reading has ever arrived", () => {
    expect(captureAgeMs(frame({}), 1_000_000)).toBeNull();
  });

  it("adds both halves, because either alone under-counts", () => {
    // The daemon can stop ticking while the socket stays up (server age grows,
    // client age does not) and the socket can drop while the daemon keeps
    // ticking (the reverse). 60 s server + 40 s client is 100 s stale — past
    // the boundary, which neither half reaches on its own.
    const now = 1_000_000;
    const age = captureAgeMs(
      frame({ capture: true, capture_age_s: 60, received_at: now - 40_000 }),
      now,
    );
    expect(age).toBe(100_000);
    expect(age! > STALE_AFTER_MS).toBe(true);
    expect((60 * 1000 > STALE_AFTER_MS) || (40_000 > STALE_AFTER_MS)).toBe(false);
  });

  it("floors at zero rather than rendering a reading from the future", () => {
    // Two clocks: the router's and this laptop's. Skew between them produced
    // "checked -5s ago" beside the headline claim.
    const now = 1_000_000;
    expect(captureAgeMs(frame({ capture: true, capture_age_s: -5, received_at: now }), now)).toBe(0);
    expect(
      captureAgeMs(frame({ capture: true, capture_age_s: 0, received_at: now + 30_000 }), now),
    ).toBe(0);
  });

  it("counts a null reading's age — a failed read still happened at a time", () => {
    const now = 1_000_000;
    expect(captureAgeMs(frame({ capture: null, capture_age_s: 12, received_at: now }), now)).toBe(
      12_000,
    );
  });
});

/* ===========================================================================
   3. The dwell — seconds AND frames
   =========================================================================== */

/** Replay a stream of metrics frames through the exact fold the store runs,
 *  and report when (if ever) the black-hole alarm first became reachable. */
function replay(
  ticks: {
    at: number;
    available: boolean;
    vpnOn?: boolean;
    applying?: boolean;
    applyingSince?: number | null;
    dropped?: boolean;
  }[],
): { firstAlarmAt: number | null; evidence: ProxyDownEvidence | null } {
  let evidence: ProxyDownEvidence | null = null;
  let firstAlarmAt: number | null = null;
  for (const t of ticks) {
    evidence = trackProxyDown(evidence, {
      frame: t.dropped ? null : { available: t.available, received_at: t.at },
      vpnOn: t.vpnOn ?? true,
      applying: t.applying ?? false,
      applyingSince: t.applyingSince ?? null,
      now: t.at,
    });
    if (firstAlarmAt == null && proxyDownDwellElapsed(evidence, t.at)) firstAlarmAt = t.at;
  }
  return { firstAlarmAt, evidence };
}

/** `count` frames at `every` ms, all saying sing-box is not answering. */
function silence(count: number, every: number, from = 0, extra = {}) {
  return Array.from({ length: count }, (_, i) => ({
    at: from + i * every,
    available: false,
    ...extra,
  }));
}

describe("the black-hole dwell", () => {
  it("needs the seconds: five frames one second apart are not enough", () => {
    const { firstAlarmAt, evidence } = replay(silence(PROXY_DOWN_MIN_FRAMES, 1_000));
    expect(evidence?.frames).toBe(PROXY_DOWN_MIN_FRAMES);
    expect(firstAlarmAt).toBeNull();
  });

  it("needs the frames: two frames 25 s apart are not enough", () => {
    // THE regression this constant exists for. A stamp subtraction elapses on
    // one `available: false`, a silent-but-open socket for 25 s (a wedged
    // daemon, a suspended tab, a slept laptop, a forward clock jump), then one
    // more frame — a dwell satisfied with no evidence in between.
    const { firstAlarmAt, evidence } = replay(silence(2, 25_000));
    expect(evidence).toEqual({ since: 0, frames: 2 });
    expect(25_000).toBeGreaterThan(PROXY_DOWN_AFTER_MS); // the seconds ARE satisfied
    expect(firstAlarmAt).toBeNull(); // and it still must not fire
  });

  it("fires when both halves are satisfied, and not one frame earlier", () => {
    const { firstAlarmAt } = replay(silence(30, 1_000));
    expect(firstAlarmAt).toBe(PROXY_DOWN_AFTER_MS);
  });

  it("makes a sparse stream wait for the frames, not just the clock", () => {
    // At a 25 s cadence the seconds are long past on frame 2; the fifth frame
    // is what unlocks it, at 100 s rather than 10.
    const { firstAlarmAt } = replay(silence(8, 25_000));
    expect(firstAlarmAt).toBe(25_000 * (PROXY_DOWN_MIN_FRAMES - 1));
  });

  it("is reset by a single frame that says sing-box answered", () => {
    const { firstAlarmAt, evidence } = replay([
      ...silence(9, 1_000),
      { at: 9_000, available: true },
      ...silence(9, 1_000, 10_000),
    ]);
    expect(firstAlarmAt).toBeNull();
    expect(evidence?.since).toBe(10_000); // the streak restarted from scratch
  });

  it("is reset by a dropped socket, which is not evidence about sing-box", () => {
    // No frame at all says the browser cannot reach the *daemon*. Counting it
    // would let a dropped WebSocket on the client's side accuse the router.
    const { evidence } = replay([
      ...silence(9, 1_000),
      { at: 9_000, available: false, dropped: true },
    ]);
    expect(evidence).toBeNull();
  });

  it("is not collected at all while the VPN is off", () => {
    // The daemon publishes `available: false` unconditionally once vpn_on is
    // false, without ever asking sing-box. Counting that would leave a stale
    // start-time that fires the instant the VPN comes back on.
    const { evidence } = replay(silence(60, 1_000, 0, { vpnOn: false }));
    expect(evidence).toBeNull();
  });

  it("carries the dwell into the headline, and nothing else does", () => {
    const facts = { vpnOn: true, capture: true as Capture, ageMs: FRESH_MS };
    expect(health({ ...facts, proxyDown: false }).level).toBe("secure");
    expect(health({ ...facts, proxyDown: true }).level).toBe("caution");
  });

  it("keeps ten seconds inside the watchdog's own repair window", () => {
    // Escalating on the first missing frame would paint a full-width amber card
    // every time the control port stutters. The watchdog re-runs
    // ensure_capture() within ~15 s and heals most of them.
    expect(PROXY_DOWN_AFTER_MS).toBeLessThan(15_000);
    expect(PROXY_DOWN_AFTER_MS).toBeGreaterThan(2_000);
  });
});

/* ===========================================================================
   4. The apply suppression bound
   =========================================================================== */

describe("`applying` may hide the alarm for a while, and not forever", () => {
  const dark = (opts: { applying: boolean; applyingSince?: number | null }) =>
    replay(silence(200, 1_000, 0, opts));

  it("hides it while an apply is genuinely in flight", () => {
    // A restart has a real gap. At 89 s of a stuck flag the dashboard is still
    // green — which is the measured P0 verbatim: vpn_on, capture true and
    // fresh, `available: false` delivered ~1/s, green the whole time.
    const { firstAlarmAt } = replay(silence(90, 1_000, 0, { applying: true, applyingSince: 0 }));
    expect(firstAlarmAt).toBeNull();
    expect(health({ vpnOn: true, capture: true, ageMs: FRESH_MS, proxyDown: false }).claim).toBe(
      CAPTURED_CLAIM,
    );
  });

  it("stops hiding it at the bound — the P0 control", () => {
    // The identical stream with the flag stuck true escalates, instead of
    // sitting green over a demonstrably dark LAN for as long as anyone watches.
    const { firstAlarmAt } = dark({ applying: true, applyingSince: 0 });
    expect(firstAlarmAt).not.toBeNull();
    expect(firstAlarmAt).toBe(APPLY_SUPPRESSES_ALARM_MS + PROXY_DOWN_AFTER_MS);
  });

  it("is the only thing standing between the LAN and the alarm", () => {
    // The control from the same measurement: identical facts, flag clear.
    const { firstAlarmAt } = dark({ applying: false });
    expect(firstAlarmAt).toBe(PROXY_DOWN_AFTER_MS);
  });

  it("suppresses up to the bound and not past it, to the millisecond", () => {
    const base = { frame: { available: false, received_at: 0 }, vpnOn: true, applying: true };
    expect(
      trackProxyDown(null, { ...base, applyingSince: 0, now: APPLY_SUPPRESSES_ALARM_MS - 1 }),
    ).toBeNull();
    expect(
      trackProxyDown(null, { ...base, applyingSince: 0, now: APPLY_SUPPRESSES_ALARM_MS }),
    ).not.toBeNull();
  });

  it("does not suppress at all without a start time to bound", () => {
    // A missing stamp must fail towards supervision, not towards silence:
    // `applying` with no known start is an unbounded suppression otherwise.
    const ev = trackProxyDown(null, {
      frame: { available: false, received_at: 0 },
      vpnOn: true,
      applying: true,
      applyingSince: null,
      now: 0,
    });
    expect(ev).toEqual({ since: 0, frames: 1 });
  });

  it("leaves room for a real apply — tens of seconds, not tens of minutes", () => {
    // An apply fetches rules, rewrites the config, restarts sing-box and waits
    // out ensure_capture. Past 90 s the flag is telling us about the daemon.
    expect(APPLY_SUPPRESSES_ALARM_MS).toBeGreaterThanOrEqual(60_000);
    expect(APPLY_SUPPRESSES_ALARM_MS).toBeLessThanOrEqual(120_000);
  });

  it("KNOWN GAP: an `applying` flag that flaps still hides it indefinitely", () => {
    // Characterisation, not an endorsement. The bound is measured from the
    // *current* apply, and a suppressed frame discards the standing evidence —
    // so a flag that re-enters before the dwell can complete resets both. Ten
    // minutes of a demonstrably dark LAN, with applying cycling 60 s on / 5 s
    // off, never reaches the alarm.
    //
    // Not reachable from the watchdog (it deliberately does not go through the
    // apply pipeline) and back-to-back applies hold the flag true rather than
    // flapping it, which is why this is recorded rather than patched: the fix
    // is a policy choice between this and the post-apply grace period, and it
    // belongs to whoever owns that trade-off. If this test ever starts failing,
    // the gap was closed — delete it.
    const ticks = [];
    for (let at = 0; at < 600_000; at += 1_000) {
      const phase = at % 65_000;
      ticks.push({
        at,
        available: false,
        applying: phase < 60_000,
        applyingSince: phase < 60_000 ? at - phase : null,
      });
    }
    expect(replay(ticks).firstAlarmAt).toBeNull();
  });
});

/* ---------------------------------------------------------------------------
   The onboarding screen may not out-vote the verdict.
   ------------------------------------------------------------------------ */

describe("mayShowOnboarding", () => {
  const LEVELS: Level[] = ["secure", "alarm", "caution", "unknown", "off"];

  it("only ever appears when health says nothing is protected", () => {
    // The screen states "no tunnel configured / Nothing is protected yet" and
    // draws the LAN → direct → WAN chain, and it hides the status pill, the
    // tabs, the dashboard and the VPN switch while it does. `off` is the only
    // level whose own claim is the same sentence.
    for (const level of LEVELS) {
      expect(mayShowOnboarding(false, level)).toBe(level === "off");
    }
  });

  it("never appears once anything is configured", () => {
    for (const level of LEVELS) {
      expect(mayShowOnboarding(true, level)).toBe(false);
    }
  });

  it("does not hide a captured LAN behind a welcome page", () => {
    // The case that motivated it: no subscriptions, but the daemon reports the
    // VPN on and the capture installed. Before, the user was shown a
    // subscription form asserting the opposite, with no switch to touch.
    const h = health({ vpnOn: true, capture: true, ageMs: 0, proxyDown: false });
    expect(h.level).toBe("secure");
    expect(mayShowOnboarding(false, h.level)).toBe(false);
  });

  it("does not hide a black-holed LAN behind a welcome page", () => {
    // Worse than the above: capture installed, sing-box gone. The whole LAN is
    // dark and the only control that clears it is the VPN switch.
    const h = health({ vpnOn: true, capture: true, ageMs: 0, proxyDown: true });
    expect(h.level).toBe("caution");
    expect(h.action?.kind).toBe("stop");
    expect(mayShowOnboarding(false, h.level)).toBe(false);
  });
});
